version: "3.8"

services:
  airflow:
    build: .
    command: >
        bash -c "
          airflow db migrate &&
          airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
          airflow scheduler &
          exec airflow webserver
        "
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////app/airflow/airflow.db
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./db:/app/db
      - ./data_lake:/app/data_lake

  streamlit:
    build: .
    command: streamlit run streamlit_app/app.py
    ports:
      - "8501:8501"
    volumes:
      - .:/app
